### ISSUE TITLE
#ask Which block of codes should I alter to call for chatGPT?

### ISSUE THREAD

**Issue by r1ddx2** [memochou1993/gpt-ai-assistant#186]
Sorry for asking stupid questions, but I am still learning how to code, and I find it very confusing to find which block of codes decides if the messages sent by the user should be answered by chatGPT or if it is just a command that the LINE bot should react to. For example, chatGPT wouldn't respond to the words "Command" or "Forget", LINE bot does.  I am not sure if the function described above falls under the "handler" folder???... I'd really appreciate it if you're willing to help me understand this problem and thanks a lot for sharing this with us!

**Comment by memochou1993** [comment]
@r1ddx2 

Hi.

Please check out the `app.js` file in the `app` folder.

GPT wouldn't respond to the words "Command", because the second command handler is just the `commandHandler`.

And if the `check` function in the `commandHandler` returns `true`, it will execute the `exec` function, and stop the whole `context` pass to next handler.

```js
const handleContext = async (context) => (
  activateHandler(context)
  || commandHandler(context)
  || continueHandler(context)
  || deactivateHandler(context)
  || deployHandler(context)
  || docHandler(context)
  || drawHandler(context)
  || forgetHandler(context)
  || enquireHandler(context)
  || reportHandler(context)
  || retryHandler(context)
  || searchHandler(context)
  || versionHandler(context)
  || talkHandler(context)
  || context
);
```

Please also see the `command.js` file in the `handlers` folder.

```js
const check = (context) => context.isCommand(COMMAND_SYS_COMMAND);
```

**Comment by r1ddx2** [comment]
Thank you so much for your quick response! I was able to solve my problem, thks a lot
